# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'revaluation_Bili' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for revaluation_Bili

end

pod 'MJRefresh'

pod 'Masonry'

pod 'SDWebImage', '~>3.7'

pod 'AFNetworking', '~> 3.1.0'

pod 'YYModel'

pod 'SVProgressHUD'

pod 'ReactiveCocoa', '~> 4.1.0'